# Dependencies
markdown:         kramdown
highlighter:         rouge

# Permalinks
permalink:        /post/:title

# Setup
title:            "Lucas"
description:      "Lucas's website."
url:              http://lucascorleone.github.io
baseurl:          "/"

author:
  name:           "Lucas (Truong)"

# Custom vars
twitter:        https://twitter.com/
github:         https://github.com/lucascorleone
