# Dependencies
markdown:         kramdown
highlighter:         rouge

# Permalinks
permalink:        /post/:title

# Setup
title:            "Lucas"
description:      "Lucas's Website."
url:              http://lucascorleone.github.io
baseurl:          "/"
version:          "0.1"

author:
  name:           "Lucas Corleone"

# Custom vars
twitter:        https://twitter.com/
github:         https://github.com/lucascorleone
